apiVersion: v1
kind: PersistentVolume
metadata:
  name: zanata-db-pv
spec:
  capacity:
    storage: 550M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/zanata-db-storage
